version: '3'

services:
  datadog-agent:
    image: datadog/agent:latest
    env_file:
      - ~/sandbox.docker.env    
    ports:
      - 127.0.0.1:8126:8126/tcp
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOG_LEVEL=TRACE 
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  app:
    build: .
    depends_on:
      - postgresql
      - datadog-agent
    environment:
      - DATABASE_URL=postgres://docker:docker@db:5432/api
      - NODE_ENV=development
      - PORT=3000
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_ANALYTICS_ENABLED=true
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
      
  postgresql:
    image: postgres
    container_name: pg-docker
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf
      - ./data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
  